### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Juyoo**

### CODE REVIEW

**Review by yodamad — COMMENTED** [review]
Why not in suricate-io.github.io ?

**Comment by Juyoo** [comment]
I also have to do it on the website. But I think that's important to have our wiki up to date

**Comment by yodamad** [comment]
It's double work, wouldn't it be more easy to add a link in our wiki to our website ?

**Comment by Juyoo** [comment]
I've made a modification on the website to add the documentation part of the widgets
See PR : https://github.com/suricate-io/suricate-io.github.io/pull/5

i'll modify the readme when the PR will be accepted

**Review by yodamad — APPROVED** [review]

**Pull request merged**
